# Generated by Django 5.1.6 on 2025-04-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yapiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
